export { default as Landing } from "./Landing"
export { default as About } from "./About"
export { default as CocktailDetails } from "./CocktailDetails"
export { default as Error } from "./Error"
export { default as HomeLayout } from "./HomeLayout"
